config/routes.rb
Myweb::Application.routes.draw do

  resources :users

  resources :projects

  resources :tasks

  resources :blogs do
    resources :comments
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  controller :user_search do
    post 'user_search' => :search
    get  'user_search' => :show
  end

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root :to => 'blogs#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Blog</a>
		by Achilles Zhang
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", '#' %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li><%= link_to "News", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" >
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "achilles' blog", '/', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", 	'/' %></li>
					<li><%= link_to "Help",		'#' %></li>
					 <% if signed_in? %>
            			<li id="fat-menu" class="dropdown">
              				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                			Account <b class="caret"></b>
              				</a>
              				<ul class="dropdown-menu">
                				<li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li><%= link_to "Time Management", tasks_path%></li>
                				<li class="divider"></li>
                				<li>
                  					<%= link_to "Sign out", signout_path, method: "delete" %>
                				</li>
              				</ul>
            			</li>
            			<% if adminitted? %>
            			<li id="fat-menu" class="dropdown">
              				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                			Management <b class="caret"></b>
              				</a>
              				<ul class="dropdown-menu">
                				<li><%= link_to "All Users", users_url %></li>
                				<li class="divider"></li>
                				<li><%= link_to "Create New Blog", new_blog_path %></li>
              				</ul>
            			</li>
                  <% end %>
          			<% else %>
            			<li><%= link_to "Sign in", signin_path %></li>
          	<% end %>

				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all",
  											"data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body style="background: rgb(248, 248, 248); ">
	<%= render 'layouts/header' %>
	<div class="container" style="width: 100%">
		<div class="container">
		<% flash.each do |key, value| %>
  			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		</div>
		<%= yield %>
		<div class="container">
		<%= render 'layouts/footer' %>
		</div>
	</div>

</body>
</html>